### ISSUE TITLE
rl_clear_history() is not working

### ISSUE THREAD

**Issue by bderya** [byaliego/minishell#27]
Invalid argument

**Comment by byaliego** [comment]
How did you test it? If you can share a screenshot, I can fix this weekend

**Comment by ayogun** [comment]
> Invalid argument

How did you test it? If you can share a screenshot, I can fix this weekend

**Comment by bderya** [comment]
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/94176553/193029024-433e0aec-2231-4eaf-bfe0-f54a0e600d86.png">
function is empty

**Comment by ayogun** [comment]
It is about Makefile. Before running the minishell, you need to update Makefile. 

First you need to install GNU readline library. You can install with brew. After you install, you need to update readline library’s path in Makefile:
![3BC614D0-2AB8-4E5F-BC39-DE2CEE0711FF](https://user-images.githubusercontent.com/62607936/193031632-dcd0add9-3ddb-4f43-8464-fda655b778c5.jpeg)
